# Generated by Django 4.2.5 on 2023-09-15 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('cover_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('pfp_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=288)),
                ('genre', models.CharField(default=None, max_length=50)),
                ('time_listened', models.DateTimeField(auto_now_add=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='api.album')),
                ('artist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='api.artist')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
    ]
